version: "3"
services:
  httpbin:
    image: kennethreitz/httpbin
    networks:
      webace_net:
        ipv4_address: 172.29.1.1

networks:
  webace_net:
    ipam:
      driver: default
      config:
      - subnet: 172.29.0.0/16