version: "3"
services:
  httpbin:
    image: kennethreitz/httpbin
    networks:
      webace_net:
        ipv4_address: 172.29.1.1

  squid:
    image: sameersbn/squid:3.5.27
    volumes:
    - ./squid/squid.conf:/etc/squid/squid.conf:ro
    networks:
      webace_net:
        ipv4_address: 172.29.1.2

  socks:
    image: serjs/go-socks5-proxy
    volumes:
    - ./squid/squid.conf:/etc/squid/squid.conf:ro
    networks:
      webace_net:
        ipv4_address: 172.29.1.3

  squid_auth:
    image: sameersbn/squid
    volumes:
    - ./squid/squid-auth.conf:/etc/squid/squid.conf:ro
    - ./squid/passwords:/etc/squid3/passwords:ro
    networks:
      webace_net:
        ipv4_address: 172.29.1.4

  socks_auth:
    image: serjs/go-socks5-proxy
    environment:
      PROXY_USER: user
      PROXY_PASSWORD: pass
    volumes:
    - ./squid/squid.conf:/etc/squid/squid.conf:ro
    networks:
      webace_net:
        ipv4_address: 172.29.1.5

networks:
  webace_net:
    ipam:
      driver: default
      config:
      - subnet: 172.29.0.0/16